import type { Subtitle } from "@/interfaces"

const subtitiles: Subtitle[] = [
  {
    id: 1,
    input_time: Date.now(),
    send_time: null,
    project_id: 1,
    project_name: "default",
    room_name: "default",
    translated_by: "用户A",
    checked_by: null,
    subtitle: "测试字幕,若一直显示此行则为连接服务器失败。",
    origin: "テストです。もしこの行がずっと表示されるままだとサーバーに接続に失敗することを示している。",
  },
  {
    id: 2,
    input_time: Date.now(),
    send_time: null,
    project_id: 1,
    project_name: "default",
    room_name: "default",
    translated_by: "用户A",
    checked_by: "用户B",
    subtitle: "此行应被显示为 -校对-未发送- 样式",
    origin: "Test 02",
  },
  {
    id: 3,
    input_time: Date.now(),
    send_time: Date.now(),
    project_id: 1,
    project_name: "default",
    room_name: "default",
    translated_by: "用户A",
    checked_by: "用户B",
    subtitle: "此行应该显示,并显示为被 -已校对-发送- 样式",
    origin: "",
  },
  {
    id: 4,
    input_time: Date.now(),
    send_time: null,
    project_id: 1,
    project_name: "default",
    room_name: "default",
    translated_by: "用户A",
    checked_by: null,
    subtitle: "此行不应该被显示,应显示全部行,未显示行交给服务器diff掉",
    origin: "",
  },
  {
    id: 5,
    input_time: Date.now(),
    send_time: Date.now(),
    project_id: 1,
    project_name: "default",
    room_name: "default",
    translated_by: "用户A",
    checked_by: null,
    subtitle: "未校对, 已发送",
    origin: "",
  },
  {
    id: 6,
    input_time: Date.now(),
    send_time: Date.now(),
    project_id: 1,
    project_name: "default",
    room_name: "default",
    translated_by: "用户A",
    checked_by: null,
    subtitle: "未校对, 已发送",
    origin: "",
  },
]

export default subtitiles
